id: PAF1CF984
initial_creation_type: ocr
source_metadata:
  volumes:
    ac4af37add2c4f268dbc49cf513165e3:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: དོན་དམ་པར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
